; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.24"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[emptyparagraphkiller][subdir] = "contrib"
projects[emptyparagraphkiller][version] = "1.0-beta2"

projects[enforce_revlog][subdir] = "contrib"
projects[enforce_revlog][version] = "1.2"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[fences][subdir] = "contrib"
projects[fences][version] = "1.0"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-alpha3"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[media_youtube][subdir] = "contrib"
projects[media_youtube][version] = "2.0-rc4"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.8"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[prepopulate][subdir] = "contrib"
projects[prepopulate][version] = "2.x-dev"

projects[tableofcontents][subdir] = "contrib"
projects[tableofcontents][version] = "2.x-dev"

projects[tagclouds][subdir] = "contrib"
projects[tagclouds][version] = "1.9"

projects[talk][subdir] = "contrib"
projects[talk][version] = "1.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[wikitools][subdir] = "contrib"
projects[wikitools][version] = "1.0-alpha1"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

; Themes
projects[zen][version] = "5.4"

; Modules
projects[freelinking][type] = "module"
projects[freelinking][download][type] = "git"
projects[freelinking][download][url] = "http://git.drupal.org/project/freelinking.git"
projects[freelinking][download][branch] = "freelinks_page"
projects[freelinking][download][revision] = "0b0c126ed9773b1798026eaf6dbd4a3d142133f4"

projects[media][type] = "module"
projects[media][download][type] = "git"
projects[media][download][url] = "http://git.drupal.org/project/media.git"
projects[media][download][branch] = "7.x-2.x"
projects[media][download][revision] = "8798bfcd24501959fc024e9b7a9b52fec98fc1d8"

; Themes
projects[siliconmeadow][type] = "theme"
projects[siliconmeadow][download][type] = "git"
projects[siliconmeadow][download][url] = "git@github.com:siliconmeadow/siliconmeadow_theme.git"
projects[siliconmeadow][download][revision] = "82f43b93babd723a3aa0a059c27645cd04281beb"

